export const BUTTON_LABELS = {
  reset: 'Сбросить',
  apply: 'Применить',
  clean: 'Очистить',
  cancel: 'Отменить',
  add: 'Добавить',
  save: 'Сохранить',
  update: 'Обновить',
  select: 'Выбрать',
  signin: 'Войти',
  signout: 'Выйти',
  download: 'Скачать',
  issue: 'Выдать',
  signature: 'Подписать',
  home: 'Главная',
  search: 'Найти',
  prevPage: 'Предыдущая страница',
  nextPage: 'Следующая страница',
  ok: 'OK',
};
