export const LABELS = {
    name: 'Название',
    department: 'Отдел',
    email: 'Email',
    password: 'Пароль',
    login: 'Имя пользователя',
    workID: 'Work-ID',
    location: 'Город',
    description: 'Описание',
    permissions: 'Разрешения',
    role: 'Роль',
    warehouse: 'Склад',
    address: 'Адрес',
    phoneNumber: 'Номер телефона',
    contractorName: 'Имя подрядчика',
    contractor: 'Подрядчик',
    use: 'Использует',
    contractorAddress: 'Адресс подрядчика',
    deviceName: 'Имя устройства',
    deviceType: 'Тип устройства',
    manufacturer: 'Производитель',
    model: 'Модель',
    serialNumber: 'Серийный номер',
    memorySize: 'Память',
    deviceWeight: 'Вес устройства(кг)',
    screenSize: 'Диагональ',
    inventoryNumber: 'Инвентарный номер',
    modelCode: 'Код модели',
    warranty: 'Гарантия',
    yes: 'Да',
    no: 'Нет',
    serviceable: 'Устройство исправно?',
    slug: 'Slug',
    startWarranty: 'Начало гарантии',
    endWarranty: 'Завершение гарантии',
    warrantyNumber: 'Номер гарантии',
    addContractor: 'Добавление подрядчика',
    userRole: 'Роль пользователя',
    userSearch: 'Поиск сотрудника',
    firstNameRu: 'Имя(ру)',
    lastNameRu: 'Фамилия(ру)',
    firstNameEn: 'Имя(анг)',
    lastNameEn: 'Фамилия(анг)',
    userLogin: 'Логин',
    accountIsActive: 'Учетная запись активна?',
    isActive: 'Активность',
    notActive: 'Неактивна',
    active: 'Активна',
    financialOptions: 'Финансовая часть',
    priceWithVat: 'Цена с НДС',
    priceWithoutVat: 'Цена без НДС',
    status: 'Состояние',
    faulty: 'Неисправно',
    normally: 'Исправно',
    addedBy: 'Добавил(а)',
    updatedBy: 'Обновил(а)',
    wasAdded: 'Дата добавления',
    wasUpdated: 'Дата обновления',
    whoAdded: 'Кто добавил',
    selectPermissions: 'Выбрать разрешения',
    inStock: 'Cклад',
    inUse: 'Oфис',









}