export const routeNameMap: Record<string, string> = {
  '': 'Главная',
  admin: 'Админ-панель',
  'add-device': 'Добавить устройство',
  users: 'Пользователи',
  settings: 'Настройки',
  locations: 'Города',
  departments: 'Управление отделами',
  contractors: 'Управление подрядчиками',
  msk: 'Москва',
  ekb: 'Екатеринбург',
  issue: 'Выдачи устройств',
  'create-issue': 'Новая выдача',
  inventory: 'Инвентаризации',
  'inventory-create': 'Новая инвентаризация',
  devices: 'Устройства',
  'add-user': 'Добавить пользователя',
  warehouses: 'Управление складами',
  'edit-device': 'Редактирование устройства',
  'add-model': 'Добавление модели',
  'add-type': 'Добавление типа',
  'add-location': 'Добавление города',
  'add-department': 'Добавление отдела',
  'add-contractor': 'Добавление подрядчика',
  'add-role': 'Добавление роли',
  'add-permission': 'Добавление разрешения',
  'add-permission_role': 'Назначение разрешения',
  access: 'Управление доступом',
  manufacturers: 'Управление производителями',
  roles: 'Управление ролями',
  permissions: 'Управление разрешениями',
  permission_roles: 'Управление доступом ролей',
};
