export const loginLabel = 'Ваш логин';
export const passwordLabel = 'Ваш пароль';
export const signin = 'Войти';
export const signout = 'Выйти';
export const fillEmail = 'Укажите почту';
export const fillPassword = 'Введите пароль';
export const enterDashboard = 'Вход в систему';
export const forgetPassword = 'Забыли пароль?';
export const reset = 'Сбросить';
export const add = 'Добавить';
export const email = 'Email';
export const password  = 'Password';
export const titleSignin = 'IT management';
export const search = 'Поиск...';
export const yes = 'Да';
export const no = 'Нет';
export const selectPhoto = 'Выбрать фото';
export const serviceable = 'Устройство исправно?'
export const addNewDeviceTitle = 'Добавление нового устройства';