export const PAGE_TITLES = {
  addContractor: 'Добавить подрядчика',
  addDepartment: 'Добавить департамент',
  addDevice: 'Добавление устройства',
  addLocation: 'Добавление локации',
  addManufacturer: 'Управление производителями',
  addModel: 'Добавление модели',
  addPermission: 'Добавление доступа',
  addRole: 'Добавление роли',
  addType: 'Добавление типа',
  addUser: 'Добавление пользователя',
  warehouses: 'Управление складами',
  calendar: 'Календарь',
  contractors: 'Подрядчики',
  device: 'Устройство',
  devices: 'Устройства',
  devicesMsk: 'Устройства МСК',
  editDevice: 'Редактирование устройства',
  grantAccess: 'Предоставление доступа',
  inventoryCreate: 'Создание инвенторизации',
  inventoryList: 'Список инвенторизаций',
  createIssue: 'Выдача устройств',
  issueList: 'Список выдач',
  knowledge: 'База знаний',
  locations: 'Локации',
  messages: 'Сообщений',
  addPermissionRole: 'Добавлений доступа роли',
  profile: 'Профайл',
  resetPassword: 'Сброс пароля',
  login: 'Логин',
  statistics: 'Статистика',
  user: 'Пользователь',
  userList: 'Список пользователей',
  home: 'Домашняя',
} as const;
