import {FC} from 'react';

const Home:FC = () => {

    return (
        <div>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        <p>welcome to dashboard</p>
        
        </div>
    );
};

export default Home;